// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/haidaqn/go-ecommerce-backend-api/global"
	"github.com/haidaqn/go-ecommerce-backend-api/internal/controller"
	"github.com/haidaqn/go-ecommerce-backend-api/internal/repo"
	"github.com/haidaqn/go-ecommerce-backend-api/internal/service"
)

// Injectors from auth.wire.go:

func InitAuthRouteHandler() (*controller.AuthController, error) {
	iUserRepository := repo.NewUserRepository()
	iUservices := service.NewUserService(iUserRepository)
	iRedisService := ProvideRedisService()
	iKafkaService := ProvideKafkaService()
	iAuthService := service.NewAuthService(iUservices, iRedisService, iKafkaService)
	authController := controller.NewAuthController(iAuthService)
	return authController, nil
}

// auth.wire.go:

func ProvideRedisService() service.IRedisService {
	return service.NewRedisService(global.Redis)
}

func ProvideKafkaService() service.IKafkaService {
	return service.NewKafkaService(global.KafkaProducer)
}
